-- ================================================================================
--Q1-- Which products in our catalog have generated over $100,000 in total revenue?
-- ================================================================================
SELECT p.product_name, SUM(o.price_usd) AS Total_Revenue
FROM orders o 
JOIN products p
ON p.product_id = o.primary_product_id
GROUP BY p.product_name
HAVING SUM(o.price_usd) > 100000
-- ==================================================================================
--Result-- The Original Mr. Fuzzy - The Forever Love Bear - The Birthday Sugar Panda
-- ==================================================================================



-- ==============================================================================================
--Q2-- How has the average order revenue evolved on a year-over-year basis between 2012 and 2015?
-- ==============================================================================================
SELECT 
    YEAR(created_at) AS Year, 
    ROUND(SUM(price_usd) / COUNT(DISTINCT order_id), 2) AS Average_Order_Value
FROM orders
GROUP BY YEAR(created_at)
ORDER BY Year;
-- ==========================
--Result--
-- 2012: $49.99
-- 2013: $52.81 (+5.6% YoY) 
-- 2014: $63.80 (+20.8% YoY)
-- 2015: $62.80 (-1.6% YoY)
-- ==========================



-- ================================================================================================================================
--Q3-- How do session volumes and repeat visitor engagement levels vary across different traffic acquisition sources (UTM sources)?
-- ================================================================================================================================
SELECT 
    COALESCE(NULLIF(utm_source, 'NULL'), 'Unknown') AS utm_source,
    COUNT(*) AS Number_of_sessions,
    SUM(CASE WHEN is_repeat_session = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS repeated_sessions_percentage
FROM website_sessions
GROUP BY COALESCE(NULLIF(utm_source, 'NULL'), 'Unknown');
-- ============================================================
--Result--
--gsearch: 316,035 Sessions | 6% Repeated Sessions Percentage
--Unknown: 83,328 Sessions | 62% Repeated Sessions Percentage
--bsearch: 62,823 Sessions | 7% Repeated Sessions Percentage
--socialbook: 10,685 Sessions | 0% Repeated Sessions Percentage
-- =============================================================



-- ============================================================================================================================================
--Q4-- Which traffic sources are driving the highest volume of sessions, focusing only on acquisition channels with over 50,000 total sessions?
-- ============================================================================================================================================
SELECT COALESCE(NULLIF(utm_source, 'NULL'), 'Unknown'),
       COUNT(*) AS Number_of_sessions
FROM website_sessions
GROUP BY utm_source
HAVING COUNT(*) > 50000;
-- =========================
--Result-- 
--gsearch: 316,035 Sessions
--Unknown: 83,328 Sessions
--bsearch: 62,823 Sessions  
-- =========================



-- ============================================================================================
--Q5-- Which product consistently ranked as the top revenue generator for each individual year?
-- ============================================================================================
WITH Product_Revenue AS(
SELECT p.product_name,
       YEAR(o.created_at) AS Year,
       ROUND(SUM(o.price_usd),2) AS Total_Revenue,
       ROW_NUMBER() OVER(PARTITION BY YEAR(o.created_at) ORDER BY SUM(o.price_usd) DESC ) AS mr
FROM products p
JOIN orders o
    ON p.product_id = o.primary_product_id
GROUP BY p.product_name, YEAR(o.created_at)
)
SELECT
    Year,
    product_name,
    Total_Revenue
FROM Product_Revenue
WHERE mr = 1
ORDER BY Year;
-- =======================================================
--Result-- 
--2012: The Original Mr. Fuzzy | $129,274.14 Total Revenue
--2013: The Original Mr. Fuzzy | $314,709.24 Total Revenue
--2014: The Original Mr. Fuzzy | $762,859.86 Total Revenue
--2015: The Original Mr. Fuzzy | $212,924.63 Total Revenue  
-- ========================================================



-- ===================================================================================================
--Q6-- What is the total revenue and corresponding refund amount generated by each individual product?
-- ===================================================================================================
SELECT p.product_name,
       ROUND(SUM(r.refund_amount_usd),2) AS Total_Refund,
       ROUND(SUM(oi.price_usd),2) AS Total_Revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
LEFT JOIN order_item_refunds r
    ON oi.order_item_id = r.order_item_id
GROUP BY p.product_name
-- =============================================================================
--Result-- 
--The Original Mr. Fuzzy: $1,211,057.78 Total Revenue $61,837.63 Total Refund
--The Forever Love Bear: $347,702.05 Total Revenue | $7,738.71 Total Refund
--The Birthday Sugar Panda: $229,260.16 Total Revenue | $13,842.99 Total Refund
--The Hudson River Mini Bear: $150,489.82 Total Revenue | $1,919.36 Total Refund 
-- ==============================================================================



-- =========================================================================
--Q7-- What percentage of overall store orders resulted in a refund request?
-- =========================================================================
SELECT
      COUNT(DISTINCT r.order_id) * 100 / COUNT(DISTINCT o.order_id) AS Refund_Order_Percentage
      FROM orders o
      LEFT JOIN order_item_refunds r
      ON o.order_id = r.order_id;
-- ============================================
--Result-- Overall Refund Order Percentage: 5% 
-- ============================================



-- ==============================================================
--Q8-- Which product generated the highest revenue for each year?
-- ==============================================================
SELECT YEAR(o.created_at) AS Year, p.product_name,
       ROUND(SUM(o.price_usd), 2) AS Total_Revenue
FROM orders o
JOIN products p
ON o.primary_product_id = p.product_id
GROUP BY YEAR(o.created_at), p.product_name
ORDER BY Total_Revenue DESC
-- ============================================
--Result--
--2012: The Original Mr. Fuzzy | $129,274.14
--2013: The Original Mr. Fuzzy | $314,709.24
--2014: The Original Mr. Fuzzy | $762,859.86
--2015: The Original Mr. Fuzzy | $212,924.63 
-- ============================================



-- ========================================================================================================
--Q9-- How are the products categorized based on their total revenue contribution across performance tiers?
-- ========================================================================================================
SELECT p.product_name,
      CASE
    WHEN SUM(o.price_usd) < 100000 THEN 'Low_Revenue'
    WHEN SUM(o.price_usd) <= 500000 THEN 'Medium_Revenue'
    ELSE 'High_Revenue'
END AS Revenue_Rank
FROM orders o
JOIN products p
ON o.primary_product_id = p.product_id
GROUP BY p.product_name
-- ============================================
--Result--
--The Original Mr. Fuzzy: High Revenue
--The Forever Love Bear: Medium Revenue
--The Birthday Sugar Panda: Medium Revenue
--The Hudson River Mini Bear: Low Revenue 
-- ============================================



-- ===================================================================================================================
--Q10-- How does the session-to-order conversion rate compare between first-time website visitors and repeat visitors?
-- ===================================================================================================================
SELECT 
    is_repeat_session,
    CAST(
        COUNT(DISTINCT o.order_id) * 100.0 
        / COUNT(DISTINCT w.website_session_id) 
        AS DECIMAL(5,2)
    ) AS Conversion_Rate
FROM website_sessions w
LEFT JOIN orders o
    ON w.website_session_id = o.website_session_id
GROUP BY is_repeat_session;
-- ============================================
--Result--
--First-Time Visitors : 6.64% Conversion Rate
--Repeat Visitors : 7.83% Conversion Rate  
-- ============================================



-- ==========================================================================================================================================
--Q11-- What is the sales performance of each product in terms of total units sold, unique orders, overall revenue, and net profit generated?
-- ==========================================================================================================================================
SELECT p.product_name,
       SUM(o.items_purchased) AS Total_Quantity_Sold,
       COUNT(o.order_id) AS Total_Orders,
       ROUND(SUM(o.price_usd),2) AS Total_Revenue,
       ROUND(SUM(o.price_usd) - SUM(o.cogs_usd), 2) AS Total_Profit
FROM orders o
JOIN products p
ON o.primary_product_id = p.product_id
GROUP BY p.product_name
ORDER BY Total_Profit DESC
-- ========================================================================================================
--Result--
--The Original Mr. Fuzzy: 29,618 Quantity Sold | 23,861 Orders | $1,419,767.87 Revenue | $879,952.06 Profit
--The Forever Love Bear: 5,682 Quantity Sold | 4,803 Orders | $318,109.19 Revenue | $200,348.01 Profit
--The Birthday Sugar Panda: 4,097 Quantity Sold | 3,068 Orders | $180,857.04 Revenue | $122,410.51 Profit
--The Hudson River Mini Bear: 628 Quantity Sold | 581 Orders | $19,775.72 Revenue | $13,429.00 Profit
-- =========================================================================================================



-- =============================================================================================================
--Q12-- What is the session-to-order conversion rate across different traffic acquisition sources (UTM sources)?
-- =============================================================================================================
SELECT COALESCE(NULLIF(w.utm_source, 'NULL'), 'Unknown') AS utm_source,
COUNT(DISTINCT o.order_id) * 100 / COUNT(DISTINCT w.website_session_id) AS Conversion_Rate
FROM website_sessions w
LEFT JOIN orders o
ON w.website_session_id = o.website_session_id
GROUP BY w.utm_source
-- ==============================
--Result--
--Unknown: 7% Conversion Rate
--bsearch: 7% Conversion Rate
--gsearch: 6% Conversion Rate
--socialbook: 3% Conversion Rate
-- ==============================



-- ==============================================================
--Q13-- Which product generated the highest total refund amount?
-- ==============================================================
SELECT p.product_name,
       ROUND(SUM(r.refund_amount_usd),2) AS Total_Refund
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
LEFT JOIN order_item_refunds r
    ON oi.order_item_id = r.order_item_id
GROUP BY p.product_name
ORDER BY p.product_name DESC
-- ==============================================================
--Result-- The Original Mr. Fuzzy: $61,837.63 Total Refund Amount
-- ==============================================================



-- =====================================================================================================================
--Q14-- What is the monthly revenue performance across the entire business timeframe from March 2012 through March 2015?
-- =====================================================================================================================
SELECT 
    YEAR(created_at) AS Year,
    MONTH(created_at) AS Month,
    SUM(price_usd) AS Monthly_Revenue
FROM orders
GROUP BY YEAR(created_at), MONTH(created_at)
ORDER BY Monthly_Revenue DESC, Year, Month;
-- ==============================
--Result--
--March 2012: $2,999.40
--April 2012: $4,949.01  
--May 2012: $5,398.92  
--June 2012: $6,998.60  
--July 2012: $8,448.31  
--August 2012: $11,397.72  
--September 2012: $14,347.13  
--October 2012: $18,546.29  
--November 2012: $30,893.82  
--December 2012: $25,294.94  
--January 2013: $19,966.10  
--February 2013: $26,515.02  
--March 2013: $19,896.15  
--April 2013: $28,584.47  
--May 2013: $29,364.29  
--June 2013: $30,544.07  
--July 2013: $31,143.96  
--August 2013: $31,373.92  
--September 2013: $32,723.65  
--October 2013: $38,242.62  
--November 2013: $46,631.02  
--December 2013: $58,262.60  
--January 2014: $56,568.89  
--February 2014: $66,012.52  
--March 2014: $68,189.73  
--April 2014: $78,725.43  
--May 2014: $88,935.27  
--June 2014: $80,051.25  
--July 2014: $83,288.55  
--August 2014: $84,716.08  
--September 2014: $92,232.49  
--October 2014: $103,905.98  
--November 2014: $128,162.98 
--December 2014: $144,823.02 
--January 2015: $132,211.54  
--February 2015: $129,212.94 
--March 2015: $78,951.07 
-- ==============================



-- =================================================================================================================================
--Q15-- Which specific months generated total revenue that exceeded the overall monthly average across the entire business timeline?
-- =================================================================================================================================
WITH avg_monthly AS
(
    SELECT
        YEAR(created_at) AS Year,
        MONTH(created_at) AS Month,
        SUM(price_usd) AS Monthly_Revenue
    FROM orders
    GROUP BY
        YEAR(created_at),
        MONTH(created_at)
)
SELECT
    Year,
    Month,
    Monthly_Revenue
FROM avg_monthly
WHERE Monthly_Revenue > (
    SELECT AVG(Monthly_Revenue)
    FROM avg_monthly
)
ORDER BY Year, Month;
-- ==============================================================
--Result--
--December 2013: $58,262.60  
--January 2014: $56,568.89  
--February 2014: $66,012.52  
--March 2014: $68,189.73  
--April 2014: $78,725.43  
--May 2014: $88,935.27  
--June 2014: $80,051.25  
--July 2014: $83,288.55  
--August 2014: $84,716.08  
--September 2014: $92,232.49  
--October 2014: $103,905.98  
--November 2014: $128,162.98  
--December 2014: $144,823.02  
--January 2015: $132,211.54  
--February 2015: $129,212.94  
--March 2015: $78,951.07
-- ==============================================================



-- ==============================================================================================================
--Q16-- What is the average selling price and average unit cost across each individual product in the portfolio?
-- ==============================================================================================================
SELECT p.product_name,
       ROUND(AVG(o.price_usd), 2) AS Average_Selling_Price,
       ROUND(AVG(o.cogs_usd), 2) AS Average_Product_Cost
FROM orders o
JOIN products p
ON o.primary_product_id = p.product_id
GROUP BY p.product_name
-- ====================================================================================
--Result--
--The Forever Love Bear: $66.23 Average Selling Price | $24.52 Average Product Cost  
--The Original Mr. Fuzzy: $59.50 Average Selling Price | $22.62 Average Product Cost  
--The Birthday Sugar Panda: $58.95 Average Selling Price | $19.05 Average Product Cost  
--The Hudson River Mini Bear: $34.04 Average Selling Price | $10.92 Average Product Cost 
-- ====================================================================================